'''
 
	This was Generated by PyQt-Ui Generator (V0.5) Advanced Framework Variant
	Created for easy access to UI code for DCC apps (Houdini, Maya)
	Initial UI should boot if all paramemters are met.
	PyQt-UI Generator is coded by Bilal Malik (Sideswipe)

'''
